apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/enforce: restricted  
    pod-security.kubernetes.io/enforce-version: v1.23
  name: system